export const SELECT_OPTION = "SELECT_OPTION";
export const FIRE_NOTIFICATION = "FIRE_NOTIFICATION";
export const GET_REQUEST = "GET_REQUEST";
export const GET_REQUEST_PENDING = "GET_REQUEST_PENDING";
export const GET_REQUEST_FAIL = "GET_REQUEST_FAIL";
export const GET_SUCCESS = "GET_SUCCESS";

export const POST_REQUEST = "POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
